### ISSUE TITLE
Potential collaboration

### ISSUE THREAD

**Issue by mottosso** [david-cattermole/assetQC#1]
Hi @david-cattermole, I like where your project is going! I'm on a similar mission, in a similar fashion, and was wondering whether you'd be interested in a collaboration of sorts?

- http://pyblish.com
- https://github.com/pyblish

**Comment by david-cattermole** [comment]
Hello @mottosso,

My deepest apologies for responding so late.

I have read about Pyblish and I am quite interested by your goals. The Pyblish project(s) are amazing. 

I have a few personal projects in the near future, but would be interested in contributing to Pyblish after that time.

Is there any specific features / bugs you'd like collaboration with?

David

**Comment by mottosso** [comment]
Not a problem @david-cattermole, thanks for getting back.

> Is there any specific features / bugs you'd like collaboration with?

Yes, there are quite a few, see [here](https://github.com/pyblish/pyblish-base/issues?q=is%3Aissue+is%3Aopen+label%3Afeature).

Such as a [web frontend](https://github.com/pyblish/pyblish-base/issues/99), [distributed publishing](https://github.com/pyblish/pyblish-base/issues/90), [plug-in arguments](https://github.com/pyblish/pyblish-base/issues/116) and [a package manager](https://github.com/pyblish/pyblish-base/issues/123).

What are your plans moving forward?

**Comment by david-cattermole** [comment]
I see my project assetQC as almost finished for what it needs to do, therefore I could put my effort into other areas. My personal projects are QT and SQL related, which I will do in my spare time for the sake of learning. 

I have a love for asset and publishing systems and so the [distributed publishing](https://github.com/pyblish/pyblish-base/issues/90), [plug-in arguments, visualise data](https://github.com/pyblish/pyblish-base/issues/116) and [dependencies and cascading updates](https://github.com/pyblish/pyblish-base/issues/113) issues sound quite promising; I don't have the experience for a [web frontend](https://github.com/pyblish/pyblish-base/issues/99). 

Another interest of mine is scene building and integration testing (with auto-renders), etc, which seems to be a direction you're going in.

If / when I contribute, I will likely start with smaller bug fixes and doc-strings if they are needed. In the past I've found these tasks allow for learning the code-base the fastest and squishing bugs (win-win).

**Comment by mottosso** [comment]
> If / when I contribute, I will likely start with smaller bug fixes and doc-strings if they are needed. In the past I've found these tasks allow for learning the code-base the fastest and squishing bugs (win-win).

That sounds wise; I wanted to highlight some of the major features to wet your appetite and paint a picture of the vision, but starting small is what I'd recommend as well.

If you hop on the [forums](http://forums.pyblish.com/) or [chat room](https://gitter.im/pyblish/pyblish), I'll introduce you to some of the other contributors of the project and then we could go from there. :)

How is your experience and/or interest in QML? The GUI could always use a pair of extra hands. https://github.com/pyblish/pyblish-qml
